data <- read.csv("threshold.txt", sep="\t", header=FALSE, col.names=c("Threshold", "Accented", "Unaccented"))
plot(data$Threshold, data$Accented, type="l", lwd=2, lty=1, xlab="Threshold", ylab="Percentage of words passing filter", ylim=c(0,100))
lines(data$Threshold, data$Unaccented, lwd="2", lty=2)
legend(x=0.35, y=50, legend=c("Accented-only paragraphs", "Unaccented paragrahps"), lwd="2", lty=c(1,2), cex=1/1.2)
dev.copy2eps(file="threshold.eps")
dev.off()

data <- read.csv("threshold_tagged.txt", sep="\t", header=FALSE, col.names=c("Threshold", "Accented", "Unaccented"))
plot(data$Threshold, data$Accented, type="l", lwd=2, lty=1, xlab="Threshold", ylab="Percentage of words passing filter", ylim=c(0,100))
lines(data$Threshold, data$Unaccented, lwd="2", lty=2)
legend(x=0.35, y=50, legend=c("Accented-only paragraphs", "Unaccented paragrahps"), lwd="2", lty=c(1,2), cex=1/1.2)
dev.copy2eps(file="threshold_tagged.eps")
dev.off()
